/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSessionsRouteImport } from './routes/_auth.sessions'
import { Route as AuthSessionsIndexRouteImport } from './routes/_auth.sessions.index'
import { Route as AuthSessionsIdRouteImport } from './routes/_auth.sessions.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsIndexRoute = AuthSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSessionsRoute,
} as any)
const AuthSessionsIdRoute = AuthSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions': typeof AuthSessionsRouteWithChildren
  '/sessions/$id': typeof AuthSessionsIdRoute
  '/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions/$id': typeof AuthSessionsIdRoute
  '/sessions': typeof AuthSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/sessions': typeof AuthSessionsRouteWithChildren
  '/_auth/sessions/$id': typeof AuthSessionsIdRoute
  '/_auth/sessions/': typeof AuthSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/sessions' | '/sessions/$id' | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sessions/$id' | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/sessions'
    | '/_auth/sessions/$id'
    | '/_auth/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sessions': {
      id: '/_auth/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthSessionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/': {
      id: '/_auth/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthSessionsIndexRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
    '/_auth/sessions/$id': {
      id: '/_auth/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthSessionsIdRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
  }
}

interface AuthSessionsRouteChildren {
  AuthSessionsIdRoute: typeof AuthSessionsIdRoute
  AuthSessionsIndexRoute: typeof AuthSessionsIndexRoute
}

const AuthSessionsRouteChildren: AuthSessionsRouteChildren = {
  AuthSessionsIdRoute: AuthSessionsIdRoute,
  AuthSessionsIndexRoute: AuthSessionsIndexRoute,
}

const AuthSessionsRouteWithChildren = AuthSessionsRoute._addFileChildren(
  AuthSessionsRouteChildren,
)

interface AuthRouteChildren {
  AuthSessionsRoute: typeof AuthSessionsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSessionsRoute: AuthSessionsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
